### ISSUE TITLE
MVP meta

### ISSUE THREAD

**Issue by dotnize** [JimTech-Solutions/memovault#1]
This is a meta-issue for tracking our MVP progress to be submitted at buildspace s5.

### Misc

- [ ] Setup & tech stack
- [ ] UI designs
- [ ] ???

### Features

- [ ] QR code generation (from profile url?)
- [ ] File uploads & tracking
- [ ] ???
